"""create initial database schema

Revision ID: 55f572e42bad
Revises:
Create Date: 2026-09-18 13:12:06.582121

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "55f572e42bad"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_keys",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("key_prefix", sa.String(length=16), nullable=False),
        sa.Column("key_digest", sa.String(length=64), nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default=sa.text("'active'"), nullable=False
        ),
        sa.Column("rate_limit_rpm", sa.Integer(), server_default=sa.text("30"), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'revoked')", name=op.f("ck_api_keys_status_allowed")
        ),
        sa.CheckConstraint("rate_limit_rpm > 0", name=op.f("ck_api_keys_positive_rate_limit")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_keys")),
        sa.UniqueConstraint("key_digest", name=op.f("uq_api_keys_key_digest")),
    )
    op.create_index("ix_api_keys_status", "api_keys", ["status"], unique=False)
    op.create_table(
        "model_pricing",
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("input_cost_per_1m_tokens", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("output_cost_per_1m_tokens", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_to > effective_from",
            name=op.f("ck_model_pricing_valid_effective_period"),
        ),
        sa.CheckConstraint(
            "input_cost_per_1m_tokens >= 0", name=op.f("ck_model_pricing_non_negative_input_cost")
        ),
        sa.CheckConstraint(
            "output_cost_per_1m_tokens >= 0", name=op.f("ck_model_pricing_non_negative_output_cost")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_pricing")),
        sa.UniqueConstraint(
            "provider", "model", "effective_from", name="provider_model_effective_from"
        ),
    )
    op.create_index(
        "ix_model_pricing_lookup",
        "model_pricing",
        ["provider", "model", "effective_from"],
        unique=False,
    )
    op.create_table(
        "llm_requests",
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("client_request_id", sa.String(length=128), nullable=True),
        sa.Column("api_key_id", sa.UUID(), nullable=False),
        sa.Column("requested_model", sa.String(length=100), nullable=False),
        sa.Column("resolved_model", sa.String(length=100), nullable=True),
        sa.Column("final_provider", sa.String(length=30), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "cache_status", sa.String(length=20), server_default=sa.text("'bypass'"), nullable=False
        ),
        sa.Column("input_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("output_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("total_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "estimated_cost_usd",
            sa.Numeric(precision=18, scale=8),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "cache_status IN ('hit', 'miss', 'bypass')",
            name=op.f("ck_llm_requests_cache_status_allowed"),
        ),
        sa.CheckConstraint(
            "status IN ('succeeded', 'failed')", name=op.f("ck_llm_requests_status_allowed")
        ),
        sa.CheckConstraint(
            "estimated_cost_usd >= 0", name=op.f("ck_llm_requests_non_negative_cost")
        ),
        sa.CheckConstraint(
            "input_tokens >= 0", name=op.f("ck_llm_requests_non_negative_input_tokens")
        ),
        sa.CheckConstraint("latency_ms >= 0", name=op.f("ck_llm_requests_non_negative_latency")),
        sa.CheckConstraint(
            "output_tokens >= 0", name=op.f("ck_llm_requests_non_negative_output_tokens")
        ),
        sa.CheckConstraint(
            "total_tokens >= 0", name=op.f("ck_llm_requests_non_negative_total_tokens")
        ),
        sa.ForeignKeyConstraint(
            ["api_key_id"],
            ["api_keys.id"],
            name=op.f("fk_llm_requests_api_key_id_api_keys"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_requests")),
        sa.UniqueConstraint("request_id", name=op.f("uq_llm_requests_request_id")),
    )
    op.create_index(
        op.f("ix_llm_requests_api_key_id"), "llm_requests", ["api_key_id"], unique=False
    )
    op.create_index("ix_llm_requests_created_at", "llm_requests", ["created_at"], unique=False)
    op.create_index("ix_llm_requests_status", "llm_requests", ["status"], unique=False)
    op.create_table(
        "llm_request_attempts",
        sa.Column("llm_request_id", sa.UUID(), nullable=False),
        sa.Column("attempt_number", sa.SmallInteger(), nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("output_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "estimated_cost_usd",
            sa.Numeric(precision=18, scale=8),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('succeeded', 'failed', 'timeout', 'rate_limited')",
            name=op.f("ck_llm_request_attempts_status_allowed"),
        ),
        sa.CheckConstraint(
            "attempt_number > 0", name=op.f("ck_llm_request_attempts_positive_attempt_number")
        ),
        sa.CheckConstraint(
            "estimated_cost_usd >= 0", name=op.f("ck_llm_request_attempts_non_negative_cost")
        ),
        sa.CheckConstraint(
            "input_tokens >= 0", name=op.f("ck_llm_request_attempts_non_negative_input_tokens")
        ),
        sa.CheckConstraint(
            "latency_ms >= 0", name=op.f("ck_llm_request_attempts_non_negative_latency")
        ),
        sa.CheckConstraint(
            "output_tokens >= 0", name=op.f("ck_llm_request_attempts_non_negative_output_tokens")
        ),
        sa.ForeignKeyConstraint(
            ["llm_request_id"],
            ["llm_requests.id"],
            name=op.f("fk_llm_request_attempts_llm_request_id_llm_requests"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_request_attempts")),
        sa.UniqueConstraint("llm_request_id", "attempt_number", name="request_attempt_number"),
    )
    op.create_index(
        op.f("ix_llm_request_attempts_llm_request_id"),
        "llm_request_attempts",
        ["llm_request_id"],
        unique=False,
    )
    op.create_index(
        "ix_llm_request_attempts_provider_status",
        "llm_request_attempts",
        ["provider", "status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_llm_request_attempts_provider_status", table_name="llm_request_attempts")
    op.drop_index(op.f("ix_llm_request_attempts_llm_request_id"), table_name="llm_request_attempts")
    op.drop_table("llm_request_attempts")
    op.drop_index("ix_llm_requests_status", table_name="llm_requests")
    op.drop_index("ix_llm_requests_created_at", table_name="llm_requests")
    op.drop_index(op.f("ix_llm_requests_api_key_id"), table_name="llm_requests")
    op.drop_table("llm_requests")
    op.drop_index("ix_model_pricing_lookup", table_name="model_pricing")
    op.drop_table("model_pricing")
    op.drop_index("ix_api_keys_status", table_name="api_keys")
    op.drop_table("api_keys")
    # ### end Alembic commands ###
